### PR TITLE
Add support for play HEv1 (SBR) and HEv2 (PS) type mp4a files (fixes issue #1)

### PR DESCRIPTION
**Pull request by compenguy**
AAC HEv1 is the same as AAC LC, but with added SBR data that can boost
the effective sampling frequency by up to 2x.  AAC HEv2 adds support for
the Parametric Stereo adds improved stere encoding efficiency at the
cost of providing only monaural audio with an LC decoder.

### CODE REVIEW

**Comment by kasper9n** [comment]
I don't know if it's a good idea to coerce SBR and PS to AAC-LC. If ADTS only allows 4 values for the audio object type, I would assume that means SBR and PS aren't supported for ADTS.

From https://en.wikipedia.org/wiki/High-Efficiency_Advanced_Audio_Coding:
> MPEG-2 and MPEG-4 AAC-LC decoders without SBR support will decode the AAC-LC part of the audio, resulting in audio output with only half the sampling frequency, thereby reducing the audio bandwidth. This usually results in the high-end, or treble, portion of the audio signal missing from the audio product.

If fdk-aac is told the audio object type is AAC-LC, does it decode with SBR support?

There are some other transports besides ADTS that fdk-aac supports, but unfortunately the fdk-aac bindings only supports ADTS:
- 0: raw access units
- 1: ADIF bitstream format
- 2: ADTS bitstream format
- 6: Audio Mux Elements (LATM) with muxConfigPresent = 1
- 7: Audio Mux Elements (LATM) with muxConfigPresent = 0, out of band StreamMuxConfig
- 10: Audio Sync Stream (LOAS)

**Comment by compenguy** [comment]
> From https://en.wikipedia.org/wiki/High-Efficiency_Advanced_Audio_Coding:
> 
> > MPEG-2 and MPEG-4 AAC-LC decoders without SBR support will decode the AAC-LC part of the audio, resulting in audio output with only half the sampling frequency, thereby reducing the audio bandwidth. This usually results in the high-end, or treble, portion of the audio signal missing from the audio product.
> 
> If fdk-aac is told the audio object type is AAC-LC, does it decode with SBR support?

Based on the "literature" I've [found around the web](https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/issues/363), generally hev1/hev2-capable decoders except for some of the embedded systems ones can detect the SBR and PS payloads attached to the AAC LC data and decode it, by means of what I'm seeing referred to as["implicit signalling"](https://www.telosalliance.com/support/A-closer-look-into-MPEG-4-High-Efficiency-AAC) (jump to section 4.2 in that page, or search for "implicit signalling").

My understanding is that [fdk-aac is capable](https://github.com/mstorsjo/fdk-aac/blob/0a90c09e00c3f6238efe8c89daf2c7e55ea4f011/libAACenc/include/aacenc_lib.h#L1456) of making use of [https://github.com/mstorsjo/fdk-aac/blob/0a90c09e00c3f6238efe8c89daf2c7e55ea4f011/libAACenc/include/aacenc_lib.h#L1414](implicit signalling).

In fact, it looks like [libav changed the default](https://libav-devel.libav.narkive.com/C4g5MdMy/rfc-patch-fdk-aac-change-the-default-sbr-ps-signaling-to-implicit) from explicit signalling (setting the right bits in the MP4 header) to implicit signalling (attaching the correctly formatted SBR payload to the frame) because explicit signalling wasn't handled correctly by some decoders.

All that's pretty suggestive but nothing definitive, I know

> There are some other transports besides ADTS that fdk-aac supports, but unfortunately the fdk-aac bindings only supports ADTS:
> 
> * 0: raw access units
> * 1: ADIF bitstream format
> * 2: ADTS bitstream format
> * 6: Audio Mux Elements (LATM) with muxConfigPresent = 1
> * 7: Audio Mux Elements (LATM) with muxConfigPresent = 0, out of band StreamMuxConfig
> * 10: Audio Sync Stream (LOAS)

Not that I'm any kind of expert, seeing as I have about a week's work of experience with AAC and MP4, but based on what I've seen digging into how a couple other encoders do things, LOAS seems to be the next most popular after ADTS, but a pretty distant second.

**Comment by kasper9n** [comment]
I believe I finally found a definitive answer, from this ["AAC Transport Formats" PDF](https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.iis.fraunhofer.de/content/dam/iis/de/doc/ame/wp/FraunhoferIIS_Application-Bulletin_AAC-Transport-Formats.pdf&ved=2ahUKEwj92qadqebvAhWm8LsIHaDnADYQFjAKegQIFxAC&usg=AOvVaw16bUaTJgl-zvwkgTGF1hBM&cshid=1617599941103):
> There are three ways HE-AAC can be signaled in a transport or storage stream. One is to do 
nothing, and rely on newer decoders to detect the extra SBR information in the AAC elementary 
bitstream. This is termed Implicit Signaling and is the only method possible for transport formats 
such as ADTS that do not include an Audio Specific Config data structure.

Will get back to this tomorrow

**Comment by kasper9n** [comment]
Looks good, I'll just change it later to not panic

**Comment by compenguy** [comment]
I wasn't sure how you'd feel about the panic vs the current behavior for unhandled types, but I figured it's easy enough to drop it if you prefer.

Thanks for all your help.

**Pull request merged**
